version: '3'
services:
  db:
    container_name: 'mysql'
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'demo'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'pass'
      MYSQL_ROOT_PASSWORD: 'pass'      
    volumes:
      - msdata:/var/lib/mysql
  web:
    build: .
    command: bash -c "python mysite/manage.py runserver 0.0.0.0:8081"
    ports:
     - "80:8081"
    depends_on:
     - db
volumes:
  msdata:     
